name: luci-app-passwall CI x86-64
on:
  #release:
  #  types: [published]
  
  push:
    branches: 
      - master

      
jobs:
  build:
    runs-on: ubuntu-18.04
    
    env:
      URL: https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64.tar.xz
    
    steps:
    - name: 检查 - 克隆储存库
      uses: actions/checkout@v1
    
    - name: 下载 and 解压 sdk
      run: |
        wget $URL
        tar xvJf openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64.tar.xz
      
    - name: 安装依赖
      run: |
        sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion git-core gcc-multilib libelf-dev autoconf automake libtool
        
    - name: 加载自定义配置
      env:
        CONFIG_FILE: '.config'
      run: |
        [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64/.config
        cd openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64
        make defconfig        
        
    - name: 克隆组件
      run: |
        cd openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64/package/
        git clone -b master https://github.com/hong0980/luci-app-passwall.git
    - name: 构建 ipk
      run: |
        cd openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64
        make package/luci-app-passwall/compile V=99
    - name: 上传 - push to artifact file
      uses: actions/upload-artifact@v1
      with:
        name: luci-app-passwall
        path: openwrt-sdk-x86-64_gcc-8.3.0_musl.Linux-x86_64/bin/packages/
